DARMA-tasking/vt-tv

- examples/example2.cc
- src/vt-tv/api/info.h
- src/vt-tv/api/object_communicator.h
- src/vt-tv/api/object_work.h
- src/vt-tv/api/phase_work.h
- src/vt-tv/render/render.cc
- src/vt-tv/render/render.h
- src/vt-tv/utility/json_reader.cc
> #13: add object communications to api, json reader and visualizations

- examples/example2.cc
- src/vt-tv/render/render.cc
> #19: Add rank qoi data to output rank_mesh

- examples/example2.cc
- src/vt-tv/render/render.cc
- src/vt-tv/utility/json_reader.cc
> #22: Clean prints

- src/vt-tv/render/render.cc
> #24: Improve object mesh creation performance

- .github/workflows/pushdockerimage.yml
> #35: Fix github secret variables names

- .github/workflows/find-trailing-whitespace.yml
- .github/workflows/pushbasedockerimage.yml
- .github/workflows/pushdockerimage.yml
> #37: change action trigger and try specifying dockerfile

- ci/build-and-test.dockerfile
> #41: switch docker image tag

- examples/example2.cc
- src/vt-tv/api/info.h
- src/vt-tv/api/phase_work.h
- src/vt-tv/api/rank.h
- src/vt-tv/render/render.cc
- src/vt-tv/render/render.h
> #40: Add qoi selection across API and rendering stage

- apps/CMakeLists.txt
- apps/vt-tv_standalone.cc
- ci/test.sh
- config/conf.yaml
- examples/example2.cc
- src/vt-tv/render/render.cc
- src/vt-tv/render/render.h
- tests/config/conf.yaml
> #26: Add configuration input for standalone app

- cmake/load_nanobind_package.cmake
> #51: Fix python version support

- src/vt-tv/utility/decompressor_base.h
> #53: Fix gcc13 build errors

- cmake/load_nanobind_package.cmake
- config/conf.yaml
- src/vt-tv/render/render.cc
- src/vt-tv/render/render.h
- src/vt-tv/utility/decompressor_base.h
- src/vt-tv/utility/parse_render.cc
- tests/config/conf.yaml
> #50 allow generation of pngs to be specified in yaml file and obeyed in parserender

- cmake/load_nanobind_package.cmake
- config/conf.yaml
- src/vt-tv/render/render.cc
- src/vt-tv/render/render.h
- src/vt-tv/utility/decompressor_base.h
- src/vt-tv/utility/parse_render.cc
- tests/config/conf.yaml
> #17 get rendering pipeline to obtain similar output to lbaf

- config/conf.yaml
- src/vt-tv/api/info.h
- src/vt-tv/api/object_communicator.h
- src/vt-tv/api/object_work.h
- src/vt-tv/api/phase_work.h
- src/vt-tv/render/render.cc
- src/vt-tv/render/render.h
- src/vt-tv/utility/parse_render.cc
> #17: Implement complete PNG rendering pipeline

- src/vt-tv/api/info.h
- src/vt-tv/render/render.cc
> #73: Fix loop through phases in Render::computeObjectQoiRange

- cmake/load_nanobind_package.cmake
- setup.py
Fixes #71 
Related to [PR 516](https://github.com/DARMA-tasking/LB-analysis-framework/pull/516) in LBAF
> #71: Add support for python 3.10 and 3.11

- cmake/vtTVConfig.cmake.in
> #81: Fix exported cmake config

- cmake/load_packages.cmake
- examples/CMakeLists.txt
Fixes #88
Prereq for vt [PR 2294](https://github.com/DARMA-tasking/vt/pull/2294)
> #88: Guard against multiple yaml-cpp installs

- src/vt-tv/api/info.h
- src/vt-tv/api/types.h
- src/vt-tv/utility/qoi_serializer.h
- tests/unit/synthetic_attributes/data.0.json
- tests/unit/synthetic_attributes/data.1.json
- tests/unit/synthetic_attributes/data.2.json
- tests/unit/synthetic_attributes/data.3.json
- tests/unit/test_json_reader.cc
Fixes #89 
Prereq for vt [#2294](https://github.com/DARMA-tasking/vt/pull/2294)
> #89: Use same QOI variant type as vt

- LICENSE
Fixes #116 
I missed the LICENSE file in PR #115
> #116: Update version number in LICENSE file

- build.sh
> #120: Build configuration error when running the non-interactive build script

- scripts/lb_datafile_schema.py
- src/vt-tv/api/info.h
- src/vt-tv/api/phase_work.h
- src/vt-tv/api/rank.h
- src/vt-tv/api/types.h
- src/vt-tv/render/render.cc
- src/vt-tv/render/render.h
- src/vt-tv/utility/json_reader.cc
- src/vt-tv/utility/json_reader.h
- tests/unit/api/test_info.cc
- tests/unit/api/test_rank.cc
- tests/unit/utility/test_json_reader.cc
> #130: api: add LB iterations: parsing and visualization

- src/vt-tv/api/info.h
- src/vt-tv/api/object_communicator.h
> #146: add missing includes

- web/README.md
- web/vt-tv-web.py
> #151: Create web-based visualizer for vt-tv outputs

- web/vt-tv-web.py
> #155: Add support for object mesh edges
